### ISSUE TITLE
NPM start has no response

### ISSUE THREAD

**Issue by gaoxt** [tonton-pixel/unicopedia-sinica#1]
I saw your project at www.electronjs.org/apps, but nothing happened after it was operated according to the Building

![企业微信截图_16391282697026](https://user-images.githubusercontent.com/25947347/145550912-b397a9cc-bf82-4848-8b13-d8d35829fb1f.png)

**Comment by tonton-pixel** [comment]
Thanks for opening this issue, and the visual information you provided.

Unfortunately, this application has never been tested under Windows, the only platforms I have access to are macOS and Linux.

It might be an init problem; it takes usually around ten seconds to launch the app, and often much more the first time a new version is run. Please try to give it more time before killing its main process by Ctrl+C.

You can also try to edit the `settings.json` file (replacing `deferredShow": true` with `deferredShow": false`), save the file and restart the application; if the main window appears (empty or not), this will be a major step forward, and watching the console output in the DevTools may provide useful hints if anything goes wrong.

**Comment by gaoxt** [comment]
Thanks for your reply.
 I started DevTools by turning on `deferredShow: False`. After the fix, I was able to successfully open it on Windows!
Submitted a fix at [#2](https://github.com/tonton-pixel/unicopedia-sinica/pull/2)

**Comment by tonton-pixel** [comment]
@gaoxt Thanks for finding how to solve this issue!

The same fix also applies to my [Unicopedia Plus](https://github.com/tonton-pixel/unicopedia-plus) application, since the modified code is a duplicate originating from it. So, I did a common update without directly using your pull request, but it has been very helpful indeed!

I guess that some end-of-line conversion happens automatically behind-the-scenes for text files, depending on the building method, cloning or downloading...
